spring:
#  profiles:
#    active: @profileActive@
  application:
    name: demo
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ip:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: user
    password: pwd


# mybatis的xml文件路径
mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/other/*.xml
  configuration:
    use-generated-keys: true

